name: Deploy GitHub Pages

on:
  push:
    branches:
      - principal   # seu branch principal
  workflow_dispatch: # habilita o botão "Run workflow"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configurar Pages
        uses: actions/configure-pages@v5

      - name: Upload de artefatos
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./front-end   # 👈 sua pasta com index.html, css, js

      - name: Deploy no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
