# O nome do seu workflow.
name: Deploy Frontend to GitHub Pages

# Dispara o workflow em eventos push na ramificação principal e manualmente.
on:
  push:
    branches:
      - main
  workflow_dispatch:

# Define um único job de implantação.
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Faz o checkout do repositório.
      - name: Checkout
        uses: actions/checkout@v4

      # Configura e implanta o site.
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend
